[package]
name = "listdb"
version = "0.1.0"
authors = ["John Hallat <jhallat@gmail.com>"]

[dependencies]
listdb-engine = { git = "https://github.com/jhallat/listdb-engine-rust"}
log = "0.4.8"
env_logger = "0.7.1"
